### ISSUE TITLE
继承C#的类型无法推断成员的类型

### ISSUE THREAD

**Issue by ps5mh** [CppCXY/EmmyLua-Unity-LS#2]
- 复现环境：
Windows10@22H2
VSCode@1.75.1
EmmyLua@0.5.11
EmmyLuaUnity@1.0.6

- 复现步骤：

```Lua
---@class Component : UnityEngine.Component
local Component = class("Component", CS.UnityEngine.Component)

---@type Component
local comp1
-- 无法提示gameObject的成员，鼠标停留在gameObject显示为any类型
local name = comp1.gameObject.

---@type UnityEngine.Component
local comp2
--可以提示出gameObject的成员
local name = comp2.gameObject.
```

我也不太确定是否应该把issue提到这。。。

**Comment by CppCXY** [comment]
如果emmylua无法正确提示,你可以换成sumneko lua

**Comment by CppCXY** [comment]
插件是可以选择注入的目标插件的

**Comment by ps5mh** [comment]
试了一下，sumneko lua确实可以！

**Comment by ps5mh** [comment]
不过sumneko提示不出来 CS.UnityEngine.MonoBehaviour. 性能也实在不好，太卡了。。。

**Comment by CppCXY** [comment]
他没提示出CS. 但是CS.UnityEngine.以后可以提示,我给他报一下

**Comment by ps5mh** [comment]
还是希望能解决emmy的问题就好了。。。或者。。。作者有没有空帮我看看
提示我一下，大概是真么原因，我去emmy的插件中看看。。。

**Comment by CppCXY** [comment]
![SMEP@TC S~P _SVWYVW9E1](https://user-images.githubusercontent.com/40318218/224640850-26e4b30d-f43c-479c-be22-5fd5f21e796a.gif)
让你解决不如让我解决

**Comment by CppCXY** [comment]
应该解决了

**Comment by ps5mh** [comment]
并没有解决吖。。。我试了一下还是不行的
Windows10@22H2
VSCode@1.76.1
EmmyLua@0.5.12
EmmyLuaUnity@1.2.3

**Comment by CppCXY** [comment]
哦我解决的不是这个问题, 先摆一会.

**Comment by ps5mh** [comment]
😅

**Comment by CppCXY** [comment]
解决了, 等会应该会有推送
