### ISSUE TITLE
无法启动插件

### ISSUE THREAD

**Issue by ps5mh** [CppCXY/EmmyLua-Unity-LS#3]
复现环境：
Windows10@22H2
VSCode@1.75.1
EmmyLua@0.5.11
EmmyLuaUnity@1.2.1
.Net7.0 SDK v7.0.201

复现步骤：
打开一个lua文件

output -> emmyluaunity plugin窗口：
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1

**Comment by CppCXY** [comment]
应该是升级后, 生成路径改了
